name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Network info
      run: ip a
    - name: Install deps
      run: sudo sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list && sudo apt-get build-dep traceroute
    - name: Build
      run: curl -L https://downloads.sourceforge.net/project/traceroute/traceroute/traceroute-2.1.3/traceroute-2.1.3.tar.gz | tar -zxv -f - && cd traceroute-2.1.3 && make
    - name: Test it maybe
      run: sudo PATH=traceroute-2.1.3/traceroute/:${PATH} bash test.sh
