name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Network info
      run: ip a && dpkg -l systemd 
    - name: Install deps
      run: "sudo sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list && sudo apt-get update && sudo apt-get build-dep traceroute && sudo apt-get install haproxy"
    - name: Get it
      run: mkdir tr && curl -L "http://sourceforge.net/projects/traceroute/best_release.json" | jq -r .release.url | xargs curl -L | tar --strip-components 1 -C tr -zxv -f -
    - name: Build it
      run: cd tr && echo "CFLAGS += -fprofile-arcs -ftest-coverage" >> Make.defines && echo "LDFLAGS += -fprofile-arcs -ftest-coverage" >> Make.defines && make
    - name: Test it maybe
      run: sudo PATH=tr/traceroute/:${PATH} bash test.sh
    - name: Report coverage
      run: cd tr/traceroute && (echo '```' && gcov -r mod-tcp.c ; echo '```') >> $GITHUB_STEP_SUMMARY
